[package]
name = "dbsync-transforms"
version = "0.1.0"
edition = "2021"

[dependencies]
dbsync-core = { path = "../core" }
lazy_static = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
